#!/bin/bash
source /cvmfs/ship.cern.ch/SHiP-2022/May/setUp.sh
alienv printenv FairShip/latest >> start_ali.sh
python run_submissions.py --output SC_config_v6_paral_reduced_warm --geofile config_v6_paral_warm_reduced.root --sub_type 3 --number 40 --input input_for_muon_prod.txt --of SC_full_opt_1
